name = "jonanda-mail"
main = "dist/index.html"
compatibility_date = "2024-09-01"

[site]
bucket = "./dist"

[env.production]
routes = [
  { pattern = "mail.jonanda.com/*", zone_name = "jonanda.com" },
  { pattern = "app.mail.jonanda.com/*", zone_name = "jonanda.com" }
]
